# Generated by Django 2.0.13 on 2019-03-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190304_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Awards',
            field=models.CharField(max_length=200),
        ),
    ]
