# Generated by Django 2.0.13 on 2019-03-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190305_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdbRating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
